version: '3.4'

services:
  socialnetwork:
    image: socialnetwork
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    env_file:
      - .env

  celery:
    image: socialnetwork
    command: celery -A social_network.celery worker -l info
    env_file:
      - .env
    depends_on:
      - rabbitmq

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    env_file:
      - .env
